server:
  #  port: 1997
  port: 1998

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ydb
    username: root
    password: Yashas@003
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update