server:
  #  port: 1359  #production & development
  port: 1997  #local

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB

  datasource:
    #cosmetic
    #url: jdbc:sqlserver://49.206.228.34:1433;databaseName=mortal_enigma;encrypt=true;trustServerCertificate=true;

    #production
    #url: jdbc:sqlserver://192.168.0.104:1433;databaseName=mortal_enigma;encrypt=true;trustServerCertificate=true;

    #development & local
    url: jdbc:sqlserver://192.168.0.105:1433;databaseName=mortal_enigma;encrypt=true;trustServerCertificate=true;

    username: sa
    password: mortalEnigma@359
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update